# Generated by Django 2.2.13 on 2022-03-24 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_tacher',
            new_name='is_teacher',
        ),
    ]
